
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 24 14:57:03 PDT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 5;
  public static final int COMA = 4;
  public static final int ENTERO = 8;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int ID = 3;
  public static final int IGUAL = 7;
  public static final int error = 1;
  public static final int FLOAT = 6;
}

