
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 25 09:03:46 PDT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLADOBLE = 9;
  public static final int FUNCTION = 39;
  public static final int PUNTOYCOMA = 12;
  public static final int MF = 57;
  public static final int MD = 59;
  public static final int CASE = 27;
  public static final int DIFERENTE = 17;
  public static final int LLAVEDER = 3;
  public static final int ARRAY = 23;
  public static final int ECHO = 22;
  public static final int FOR = 38;
  public static final int STATIC = 51;
  public static final int CORCHETEIZQ = 6;
  public static final int MENORIGUAL = 47;
  public static final int AND = 24;
  public static final int ELSEIF = 31;
  public static final int IGUAL = 16;
  public static final int ENDSWITCH = 34;
  public static final int NOIDENTICO = 46;
  public static final int CARACTER = 58;
  public static final int LETRA = 53;
  public static final int OR = 25;
  public static final int INCREMENTO = 42;
  public static final int ENDFOR = 32;
  public static final int IF = 40;
  public static final int ENDWHILE = 35;
  public static final int PARENTESISIZQ = 4;
  public static final int IDENTICO = 45;
  public static final int MAYORIGUAL = 44;
  public static final int COMILLASIMPLE = 8;
  public static final int EOF = 0;
  public static final int RETURN = 50;
  public static final int DECREMENTO = 41;
  public static final int error = 1;
  public static final int DIGITO = 52;
  public static final int INCLUDE = 43;
  public static final int COMA = 11;
  public static final int CADENA = 54;
  public static final int MENOS = 19;
  public static final int MENOR = 14;
  public static final int BREAK = 26;
  public static final int SWITCH = 36;
  public static final int ASIGNACION = 15;
  public static final int MAYOR = 13;
  public static final int ENDIF = 33;
  public static final int CORCHETEDER = 7;
  public static final int ELSE = 30;
  public static final int PUNTO = 10;
  public static final int VARIABLE = 56;
  public static final int WHILE = 37;
  public static final int FINAL = 28;
  public static final int LLAVEIZQ = 2;
  public static final int FLOAT = 55;
  public static final int INICIO = 48;
  public static final int PARENTESISDER = 5;
  public static final int DIVISION = 21;
  public static final int PRINT = 49;
  public static final int DO = 29;
  public static final int MULTIPLICACION = 20;
  public static final int MAS = 18;
}

